SELECT TOP (1000) [Column_1]
      ,[NAME]
      ,[FOLLOWERS]
      ,[ER]
      ,[COUNTRY]
      ,[TOPIC_OF_INFLUENCE]
      ,[POTENTIAL_REACH]
      ,[channel_name]
      ,[total_subscribers]
      ,[total_views]
      ,[total_videos]
  FROM [youtube_db].[dbo].[updated_youtube_data_co]
